//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoExample.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testEntities : DbContext
    {
        public testEntities()
            : base("name=testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<AutoSale> AutoSales { get; set; }
        public virtual DbSet<ExampleAdo> ExampleAdoes { get; set; }
        public virtual DbSet<Friend> Friends { get; set; }
        public virtual DbSet<Home> Homes { get; set; }
        public virtual DbSet<Personal> Personals { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ExampleAdoNet> ExampleAdoNets { get; set; }
        public virtual DbSet<Auto> Autos { get; set; }
    }
}
